datasets:
  arxiv:
    path: ./data/arxiv
    weight: 0.08333333333333333
  cosmopedia:
    path: ./data/cosmopedia
    weight: 0.08333333333333333
  evol_instruct_code:
    path: ./data/evol_instruct_code
    weight: 0.3333333333333333
  factuality_source:
    path: ./data/factuality_source
    weight: 0.08333333333333333
  japanese_instruct:
    path: ./data/japanese_instruct
    weight: 0.16666666666666666
  wiki_ja:
    path: ./data/wiki_ja
    weight: 0.16666666666666666
  wikitext103:
    path: ./data/wikitext103
    weight: 0.08333333333333333
